site_name: PicoGlitcher / findus
nav:
  - Home: index.md
  - Overview: overview.md
  - Getting Started: getting_started.md
  - Examples: examples.md
  - Command Line Tools: cli.md
  - Findus: findus.md
  - BootloaderCom: bootloadercom.md
  - mpGlitcher: mpglitcher.md
  - Customize your Pico Glitcher: code.md
theme: readthedocs
plugins:
  - search
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
  - autorefs