site_name: PicoGlitcher / findus
nav:
  - Home: index.md
  - Findus: findus.md
theme: readthedocs
plugins:
  - search
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
  - autorefs