[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "findus"
authors = [{name = "Matthias Kesenheimer", email = "m.kesenheimer@gmx.net"}]
dynamic = ["version", "description"]