[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.setuptools]
packages = ["findus"]

[project]
name = "findus"
description = "Library to perform fault injection attacks with the PicoGlitcher, Chipwhisperer Husky or Chipwhisperer Pro"
version = "0.9.2"
license = {file = "LICENSE"}
authors = [{name = "Matthias Kesenheimer", email = "m.kesenheimer@gmx.net"}]
dependencies = [
  "setuptools",
  "adafruit-ampy",
  "pyserial",
  "termcolor",
  "plotly",
  "pandas",
  "dash",
  "dash_bootstrap_components",
  "minimalmodbus",
]
#"chipwhisperer",

[project.urls]
Homepage = "https://mkesenheimer.github.io"
Documentation = "https://fault-injection-library.readthedocs.io/en/latest/"
Repository = "https://github.com/MKesenheimer/fault-injection-library.git"
Issues = "https://github.com/MKesenheimer/fault-injection-library/issues"